import type { Metadata } from "next";
import { poppins } from "../themes/fonts";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import FooterComponent from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased overflow-x-hidden`}
      >
        <NavbarComponent></NavbarComponent>
        {children}
        <FooterComponent></FooterComponent>
      </body>
    </html>
  );
}
