"use client";

// import type { Metadata } from "next";
import { poppins } from "../themes/fonts";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import FooterComponent from "@/components/Footer";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const noNavbar = ["/login", "/register", "/admin"];
  const noFooter = ["/login", "/register", "/admin"];

  const pathname = usePathname();

  return (
    <html lang="en">

      <body
        className={`${poppins.className} antialiased overflow-x-hidden`}
      >

          {
            !noNavbar.includes(pathname) &&
            <NavbarComponent></NavbarComponent>
          }
          {children}
          {
            !noFooter.includes(pathname) &&
            <FooterComponent></FooterComponent>
          }

      </body>
    </html>
  );
}
